### ISSUE TITLE
Can you please create a new release for version 5.0.0?

### ISSUE THREAD

**Issue by YuvalNaturalInt** [suweller/mongoid-autoinc#25]
Can you please create a new release for version 5.0.0?
Thanks
Yuval

**Comment by thiensubs** [comment]
+1

**Comment by alexkravets** [comment]
+1

**Comment by bejmuller** [comment]
+1

**Comment by andreale** [comment]
+1

**Comment by lucke84** [comment]
+1

**Comment by rjurado01** [comment]
+1

**Comment by suweller** [comment]
Does `mongoid-autoinc` work on Mongoid 5.0 or is additional work needed to make it work?

**Comment by alexkravets** [comment]
It does work.

**Comment by thiensubs** [comment]
I'm so tired with this release of this gems.  In rubygems it only version 4. :-1:

**Comment by suweller** [comment]
https://rubygems.org/gems/mongoid-autoinc/versions/5.0.1

**Comment by alexkravets** [comment]
:+1:

**Comment by suweller** [comment]
Sorry to make you guys wait. I rarely use `mongoid` during work hours, and have a lot less free time than I used to have. I'd be happy to have someone collaborate with me in order to make it a more active project, and above all, keep it fun. ^_^
