### ISSUE TITLE
Incompatible with Mongoid 5.1.1

### ISSUE THREAD

**Issue by roaringskyinc** [suweller/mongoid-autoinc#28]
Autoinc 5.0.1 works with Mongoid 5.0.0 but not the latest (5.1.1) release. ~~Submitted a pull request, even though ``~>`` is supposed to be equivalent to ``>=``. Not sure where the incompatibility lies - still looking.~~

Update:

This is fixed in the pull request by changing ``~> 5.0.0`` to ``~> 5.0``. Using 5.0.0 implies Mongoid compatibility of version 5.0.x, whereas using 5.0 implies compatibility with 5.x.

**Comment by suweller** [comment]
The related pull-request (#27 ), so I'm closing this too.
