### ISSUE TITLE
Mongoid 6 Support

### ISSUE THREAD

**Issue by groe** [suweller/mongoid-autoinc#30]
Mongoid-autoinc currently only supports Mongoid 5. Are there any plans for Mongoid 6 support (which is required for Rails 5+)?

**Comment by suweller** [comment]
I'd be happy to merge a pull-request which adds Mongoid 6.x support. This will get you what you want, and an honourable mention on the contributors list. :)
I probably have time in about two weeks, after I finish renovations on my house.

As a side-note: It could very well be that it already works, but once you optimistically publish a gem (`>=`), some people really assume magical foresight of this small codebase. :)

**Comment by suweller** [comment]
I had some time today after all, please check if [`mongoid-autoinc v6.0.0.rc0`] (https://rubygems.org/gems/mongoid-autoinc/versions/6.0.0.rc0) works for you, @groe 
I hope it does, otherwise I could really use some help on that pull-request.

**Comment by groe** [comment]
Thank you @suweller!

I've only been using `mongoid-autoinc` as a dependency for `rpush-mongoid` (see https://github.com/rpush/rpush-mongoid/issues/3), so unfortunately I don't have an isolated testcase for this until rpush-mongoid is compatible as well...

**Comment by sahilchopra** [comment]
+1

**Comment by suweller** [comment]
@sahilchopra I'm not sure what +1 means. The status from my end is, there is a release candidate. Does it work? If so, we can release it as v6.0.0. 

[Check my previous comment](https://github.com/suweller/mongoid-autoinc/issues/30#issuecomment-241438648). It points to a mongoid-autoinc version which (for me) worked with Mongoid 6.

**Comment by onomated** [comment]
@suweller I've verified this against mongoid 6.0 release version

**Comment by suweller** [comment]
I've released 6.0.0
