### ISSUE TITLE
Undefined method 'attr_protected' for Class

### ISSUE THREAD

**Issue by VicenteRD** [suweller/mongoid-autoinc#32]
I'm getting the error when calling increments :var .
(Ruby 2.3, Rails 5.0.1, Mongoid 6)

Looking at the source I can see you're using `attr_protected`, which is no longer used.
http://stackoverflow.com/questions/17371334/how-is-attr-accessible-used-in-rails-4

I've also attached screenshot of the error screen

Am I doing something wrong?

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/7538743/22345538/357460d6-e3df-11e6-838f-6bf56d2ae879.png)

**Comment by suweller** [comment]
This was guarded since commit (953aa833c3c37b6910f01fcdd63c414d859f785b),
which is included in `v6.0.0.rc0`, `v5.0.2`, `v5.0.1`, and `v4.0.0`.

What version are you using?

**Comment by VicenteRD** [comment]
6.0.0 if I recall correctly. But it seems to be a Rails version issue.
They're no longer using `attr_protected` in favor of strong parameters.
I've managed to get a copy of your code working within my project, but I don't consider it an elegant solution, and I kind of didn't ask for permission...

**Comment by VicenteRD** [comment]
Sorry, straight from the Gemfile
`gem 'rails', '~> 5.0.1'`

`gem 'mongoid', '~> 6.0', '>= 6.0.3'`

**Comment by suweller** [comment]
I'm sorry for being unclear in my initial response. I meant which version of `mongoid-autoinc`  are you using. I'm quite sure it does not assume `attr_protected` to be there. At least for the versions I've mentioned above.

**Comment by VicenteRD** [comment]
Oh, oops, sorry.
I did not specify a version in the Gemfile... I'm guessing latest ?

**Comment by suweller** [comment]
I've released  [v6.0.0](https://github.com/suweller/mongoid-autoinc/releases/tag/v6.0.0). I hope that, if you run `bundle update mongoid-autoinc` your problems will go away.
Since I have no specific gem version for this gem, this is the best I can do for you.

**Comment by VicenteRD** [comment]
It works like a charm, I'm sorry for the ambiguity of my responses :/

Thanks a bunch!!
