### ISSUE TITLE
Update Mongoid dependency 

### ISSUE THREAD

**Issue by EhsanZ** [suweller/mongoid-autoinc#34]
Hi

Can you please update Mongoid that you depend on to `6.1.0` since it is the last stable mongoid version?

**Comment by suweller** [comment]
My apologies. I [released a fix](https://github.com/suweller/mongoid-autoinc/releases/tag/v6.0.2) for this but forgot to let you know about it here. This version should be able to (try) to be compatible with any of the mongoid `6.x` versions.
`gem install mongoid-autoinc` should get the right version.
